import type { IProvider } from '../../core/provider';
import type { RadioData } from './RadioTypes';

// Porteo textual de RADIO_DATA_FALLBACK (src/services/radioService.ts) —
// catálogo completo con streams verificados. Fuentes: gist YoSoyGena 2026,
// SomaFM, NPR, KAN, BBC, WBGO, WRTI.
const RADIO_DATA_FALLBACK: RadioData = {
  categorias: [
    { id: 'cat-noticias', nombre: 'Noticias', emoji: '📰', orden: 1 },
    { id: 'cat-musica', nombre: 'Música', emoji: '🎵', orden: 2 },
    { id: 'cat-folklore', nombre: 'Folklore', emoji: '💃', orden: 3 },
    { id: 'cat-clasica', nombre: 'Clásica', emoji: '🎻', orden: 4 },
    { id: 'cat-deportes', nombre: 'Deportes', emoji: '⚽', orden: 5 },
    { id: 'cat-general', nombre: 'General', emoji: '📻', orden: 6 },
    { id: 'cat-tango', nombre: 'Tango', emoji: '🕺', orden: 7 },
  ],
  paises: [
    { id: 'p-ar', codigo: 'AR', nombre: 'Español', emojiBandera: '🇦🇷', orden: 1 },
    { id: 'p-il', codigo: 'IL', nombre: 'Hebreo', emojiBandera: '🇮🇱', orden: 2 },
    { id: 'p-us', codigo: 'US', nombre: 'Inglés', emojiBandera: '🇺🇸', orden: 3 },
  ],
  radios: [
    {
      id: 'ar-nacional', nombre: 'Radio Nacional', descripcion: 'Radio pública argentina · AM 870',
      urlStream: 'https://sa.mp3.icecast.magma.edge-access.net/sc_rad1',
      urlFallback: 'http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad1',
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Noticias', esDestacada: true,
      categoriaId: 'cat-noticias', categoria: 'Noticias', categoriaEmoji: '📰',
    },
    {
      id: 'ar-radio10', nombre: 'Radio 10', descripcion: 'Noticias y debate · AM 710',
      urlStream: 'https://radio10.stweb.tv/radio10/live/chunks.m3u8',
      urlFallback: 'https://s6.stweb.tv/radio10/live/playlist.m3u8',
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Noticias', esDestacada: true,
      categoriaId: 'cat-noticias', categoria: 'Noticias', categoriaEmoji: '📰',
    },
    {
      id: 'ar-mitre', nombre: 'Radio Mitre', descripcion: 'Noticias, política y actualidad · AM 790',
      urlStream: 'https://playerservices.streamtheworld.com/api/livestream-redirect/AM790_56AAC.aac',
      urlFallback: 'https://buecrplb01.cienradios.com.ar/Mitre790.aac',
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Noticias', esDestacada: true,
      categoriaId: 'cat-noticias', categoria: 'Noticias', categoriaEmoji: '📰',
    },
    {
      id: 'ar-lared', nombre: 'La Red', descripcion: 'Deportes y noticias · AM 910',
      urlStream: 'https://playerservices.streamtheworld.com/api/livestream-redirect/LA_RED_AM910AAC.aac',
      urlFallback: null,
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Noticias', esDestacada: false,
      categoriaId: 'cat-noticias', categoria: 'Noticias', categoriaEmoji: '📰',
    },
    {
      id: 'ar-cooperativa', nombre: 'Radio Cooperativa', descripcion: 'Noticias y periodismo independiente · AM 770',
      urlStream: 'https://cdn.instream.audio:9582/stream',
      urlFallback: null,
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Noticias', esDestacada: false,
      categoriaId: 'cat-noticias', categoria: 'Noticias', categoriaEmoji: '📰',
    },
    {
      id: 'ar-stream950', nombre: 'StreAM 950', descripcion: 'Información y entretenimiento · AM 950',
      urlStream: 'https://unlimited2-ar.dps.live/cnn-ar/aac/icecast.audio',
      urlFallback: null,
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Noticias', esDestacada: false,
      categoriaId: 'cat-noticias', categoria: 'Noticias', categoriaEmoji: '📰',
    },
    {
      id: 'ar-la100', nombre: 'La 100', descripcion: 'Los mejores hits · FM 99.9',
      urlStream: 'https://playerservices.streamtheworld.com/api/livestream-redirect/FM999_56.mp3',
      urlFallback: 'https://buecrplb01.cienradios.com.ar/la100.aac',
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Pop', esDestacada: true,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'ar-aspen', nombre: 'Aspen FM', descripcion: 'Pop y rock en inglés · FM 102.3',
      urlStream: 'https://playerservices.streamtheworld.com/api/livestream-redirect/ASPEN.mp3',
      urlFallback: null,
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Pop/Rock', esDestacada: true,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'ar-blue', nombre: 'Blue FM', descripcion: 'Música suave y pop · FM 100.7',
      urlStream: 'https://playerservices.streamtheworld.com/api/livestream-redirect/BLUE_FM_100_7AAC.aac',
      urlFallback: null,
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Pop', esDestacada: true,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'ar-metro', nombre: 'Metro FM', descripcion: 'Música y entretenimiento · FM 95.1',
      urlStream: 'https://playerservices.streamtheworld.com/api/livestream-redirect/METRO.mp3',
      urlFallback: null,
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Pop/Hits', esDestacada: false,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'ar-rockpop', nombre: 'Rock & Pop', descripcion: 'Rock y pop en español · FM 95.9',
      urlStream: 'https://playerservices.streamtheworld.com/api/livestream-redirect/ROCKANDPOPAAC.aac',
      urlFallback: null,
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Rock/Pop', esDestacada: true,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'ar-nacional-rock', nombre: 'Nacional Rock', descripcion: 'Rock nacional · FM 93.7',
      urlStream: 'https://sa.mp3.icecast.magma.edge-access.net/sc_rad39',
      urlFallback: 'http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad39',
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Rock', esDestacada: false,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'ar-urbana', nombre: 'Urbana Play', descripcion: 'Pop, rock y actualidad · FM 104.3',
      urlStream: 'https://cdn.instream.audio:9660/stream',
      urlFallback: 'http://cdn.instream.audio:9660/stream',
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Pop/Rock', esDestacada: true,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'ar-la2x4', nombre: 'La 2x4', descripcion: 'La única radio de tango del mundo · FM 92.7 · GCBA',
      urlStream: 'https://media.radios.ar:9270/stream',
      urlFallback: 'http://radios.argentina.fm:9270/stream',
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Tango', esDestacada: true,
      categoriaId: 'cat-tango', categoria: 'Tango', categoriaEmoji: '🕺',
    },
    {
      id: 'ar-rivadavia', nombre: 'Radio Rivadavia', descripcion: 'Tango, folklore y nostalgia · AM 630',
      urlStream: 'https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC.aac',
      urlFallback: 'https://streammax.alsolnet.com/radiorivadavia',
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Tango/Folklore', esDestacada: true,
      categoriaId: 'cat-tango', categoria: 'Tango', categoriaEmoji: '🕺',
    },
    {
      id: 'ar-folklorica', nombre: 'Nacional Folklórica', descripcion: 'Folklore argentino · FM 98.7',
      urlStream: 'https://sa.mp3.icecast.magma.edge-access.net/sc_rad38',
      urlFallback: 'http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad38',
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Folklore', esDestacada: true,
      categoriaId: 'cat-folklore', categoria: 'Folklore', categoriaEmoji: '💃',
    },
    {
      id: 'ar-am750', nombre: 'AM 750', descripcion: 'Folklore, cultura y política · AM 750',
      urlStream: 'https://playerservices.streamtheworld.com/api/livestream-redirect/AM750AAC.aac',
      urlFallback: null,
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Folklore/Noticias', esDestacada: false,
      categoriaId: 'cat-folklore', categoria: 'Folklore', categoriaEmoji: '💃',
    },
    {
      id: 'ar-clasica', nombre: 'Nacional Clásica', descripcion: 'Música clásica · FM 96.7',
      urlStream: 'https://sa.mp3.icecast.magma.edge-access.net/sc_rad37',
      urlFallback: 'http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad37',
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Clásica', esDestacada: true,
      categoriaId: 'cat-clasica', categoria: 'Clásica', categoriaEmoji: '🎻',
    },
    {
      id: 'ar-dsports', nombre: 'D Sports Radio', descripcion: 'Deportes en vivo · FM 103.1',
      urlStream: 'https://playerservices.streamtheworld.com/api/livestream-redirect/DSPORTSRADIOAAC_SC',
      urlFallback: null,
      urlLogo: null, pais: 'AR', paisNombre: 'Español', paisEmoji: '🇦🇷',
      ciudad: 'Buenos Aires', genero: 'Deportes', esDestacada: true,
      categoriaId: 'cat-deportes', categoria: 'Deportes', categoriaEmoji: '⚽',
    },
    {
      id: 'il-glz', nombre: 'Galei Tzahal', descripcion: 'Radio del ejército israelí · noticias y música',
      urlStream: 'https://glzwizzlv.bynetcdn.com/glz_mp3',
      urlFallback: 'https://glzwizzlv.bynetcdn.com/glz_aac',
      urlLogo: null, pais: 'IL', paisNombre: 'Hebreo', paisEmoji: '🇮🇱',
      ciudad: 'Tel Aviv', genero: 'General', esDestacada: true,
      categoriaId: 'cat-general', categoria: 'General', categoriaEmoji: '📻',
    },
    {
      id: 'il-galgalatz', nombre: 'Galgalatz', descripcion: 'Hits internacionales y música israelí · FM 91.8',
      urlStream: 'https://glzwizzlv.bynetcdn.com/glglz_mp3',
      urlFallback: 'https://glzwizzlv.bynetcdn.com/glz_mp3',
      urlLogo: null, pais: 'IL', paisNombre: 'Hebreo', paisEmoji: '🇮🇱',
      ciudad: 'Tel Aviv', genero: 'Pop', esDestacada: true,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'il-kan88', nombre: 'Kan 88', descripcion: 'Rock, jazz y música alternativa israelí',
      urlStream: 'https://kan88wizzlv.bynetcdn.com/kan88_mp3',
      urlFallback: 'https://kan88wizzlv.bynetcdn.com/kan88_aac',
      urlLogo: null, pais: 'IL', paisNombre: 'Hebreo', paisEmoji: '🇮🇱',
      ciudad: 'Jerusalén', genero: 'Rock/Jazz', esDestacada: false,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'us-npr', nombre: 'NPR News', descripcion: 'Radio pública de noticias · Washington',
      urlStream: 'https://npr-ice.streamguys1.com/live.mp3',
      urlFallback: 'https://stream.npr.org/anon.npr-mp3-128',
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'Washington', genero: 'Noticias', esDestacada: true,
      categoriaId: 'cat-noticias', categoria: 'Noticias', categoriaEmoji: '📰',
    },
    {
      id: 'gb-bbc', nombre: 'BBC World Service', descripcion: 'Noticias mundiales en inglés · BBC',
      urlStream: 'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service',
      urlFallback: null,
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'Londres', genero: 'Noticias', esDestacada: true,
      categoriaId: 'cat-noticias', categoria: 'Noticias', categoriaEmoji: '📰',
    },
    {
      id: 'us-wrti', nombre: 'Clásica Relajante', descripcion: 'Música clásica instrumental · WRTI Philadelphia',
      urlStream: 'https://wrti-live.streamguys1.com/classical-mp3',
      urlFallback: 'https://stream.wqxr.org/wqxr',
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'Filadelfia', genero: 'Clásica', esDestacada: true,
      categoriaId: 'cat-clasica', categoria: 'Clásica', categoriaEmoji: '🎻',
    },
    {
      id: 'us-wqxr', nombre: 'WQXR', descripcion: 'Clásica de Nueva York · 105.9 FM',
      urlStream: 'https://stream.wqxr.org/wqxr',
      urlFallback: null,
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'Nueva York', genero: 'Clásica', esDestacada: true,
      categoriaId: 'cat-clasica', categoria: 'Clásica', categoriaEmoji: '🎻',
    },
    {
      id: 'us-soma-illstreet', nombre: 'Illinois Street Lounge', descripcion: 'Lounge vintage, era Sinatra y exotica · SomaFM',
      urlStream: 'https://ice6.somafm.com/illstreet-128-mp3',
      urlFallback: 'https://ice4.somafm.com/illstreet-128-mp3',
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'San Francisco', genero: 'Lounge/Vintage', esDestacada: true,
      categoriaId: 'cat-clasica', categoria: 'Clásica', categoriaEmoji: '🎻',
    },
    {
      id: 'us-wbgo', nombre: 'Jazz & Blues', descripcion: 'Jazz y blues clásico · WBGO Newark NPR',
      urlStream: 'https://ais-sa8.cdnstream1.com/3629_128.mp3',
      urlFallback: 'https://ais-sa8.cdnstream1.com/3630_128.mp3',
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'Newark', genero: 'Jazz', esDestacada: true,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'us-soma-sonicuniverse', nombre: 'Sonic Universe', descripcion: 'Jazz ecléctico y avant-garde · SomaFM',
      urlStream: 'https://ice6.somafm.com/sonicuniverse-128-mp3',
      urlFallback: 'https://ice4.somafm.com/sonicuniverse-128-mp3',
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'San Francisco', genero: 'Jazz', esDestacada: false,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'us-soma-secret', nombre: 'Secret Agent', descripcion: 'Lounge y big band estilo 007 · SomaFM',
      urlStream: 'https://ice6.somafm.com/secretagent-128-mp3',
      urlFallback: 'https://ice4.somafm.com/secretagent-128-mp3',
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'San Francisco', genero: 'Lounge/Spy Jazz', esDestacada: false,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'us-soma-7soul', nombre: 'Soul Vintage', descripcion: 'Soul clásico de los 50s–70s · SomaFM',
      urlStream: 'https://ice6.somafm.com/7soul-128-mp3',
      urlFallback: 'https://ice4.somafm.com/7soul-128-mp3',
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'San Francisco', genero: 'Soul/R&B', esDestacada: false,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'us-soma-seventies', nombre: '70s Radio', descripcion: 'Rock melódico y soft rock de los 70s · SomaFM',
      urlStream: 'https://ice6.somafm.com/seventies-128-mp3',
      urlFallback: 'https://ice4.somafm.com/seventies-128-mp3',
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'San Francisco', genero: 'Rock/70s', esDestacada: false,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
    {
      id: 'us-soma-groove', nombre: 'Groove Salad', descripcion: 'Ambient y chillout · SomaFM',
      urlStream: 'https://ice6.somafm.com/groovesalad-128-mp3',
      urlFallback: 'https://ice4.somafm.com/groovesalad-128-mp3',
      urlLogo: null, pais: 'US', paisNombre: 'Inglés', paisEmoji: '🇺🇸',
      ciudad: 'San Francisco', genero: 'Ambient', esDestacada: false,
      categoriaId: 'cat-musica', categoria: 'Música', categoriaEmoji: '🎵',
    },
  ],
};

/** Provider tier 2 — catálogo hardcodeado, se usa si Supabase falla o devuelve vacío. */
export class HardcodedRadioCatalogProvider implements IProvider<void, RadioData> {
  readonly name = 'radio-catalog:hardcoded';
  readonly tier = 2;

  async call(): Promise<RadioData> {
    return RADIO_DATA_FALLBACK;
  }
}
