-- ============================================================
-- ElderTech — Imagen por paso en los tutoriales de la biblioteca v2
-- La v2 (20260915130000) cargó los 20 tutoriales sin imagen_url en los pasos,
-- así que la app mostraba solo el ícono de la categoría. Acá cada paso recibe
-- una foto temática (loremflickr, mismo esquema que usa TutorialImage; si no
-- carga cae a picsum y después al ícono). `lock` fija la foto para que no
-- cambie en cada apertura. Solo toca pasos sin imagen cargada a mano.
-- Fecha: 2026-10-04
-- ============================================================

UPDATE pasos_tutorial p
SET imagen_url = 'https://loremflickr.com/640/420/' || k.tags || '?lock=' || k.lock_id
FROM (VALUES
  ('Cómo enviar un mensaje por WhatsApp', 1, 'whatsapp,smartphone', 1),
  ('Cómo enviar un mensaje por WhatsApp', 2, 'chat,smartphone,contacts', 2),
  ('Cómo enviar un mensaje por WhatsApp', 3, 'typing,smartphone,keyboard', 3),
  ('Cómo enviar un mensaje por WhatsApp', 4, 'sending,message,smartphone', 4),
  ('Cómo enviar un mensaje por WhatsApp', 5, 'reading,message,smartphone', 5),
  ('Cómo mandar un audio por WhatsApp', 1, 'whatsapp,chat,smartphone', 6),
  ('Cómo mandar un audio por WhatsApp', 2, 'microphone,smartphone', 7),
  ('Cómo mandar un audio por WhatsApp', 3, 'recording,voice,microphone', 8),
  ('Cómo mandar un audio por WhatsApp', 4, 'voice,message,smartphone', 9),
  ('Cómo mandar un audio por WhatsApp', 5, 'cancel,swipe,smartphone', 10),
  ('Cómo hacer una videollamada por WhatsApp', 1, 'whatsapp,chat,smartphone', 11),
  ('Cómo hacer una videollamada por WhatsApp', 2, 'video,call,smartphone', 12),
  ('Cómo hacer una videollamada por WhatsApp', 3, 'waiting,phone,call', 13),
  ('Cómo hacer una videollamada por WhatsApp', 4, 'video,call,family', 14),
  ('Cómo hacer una videollamada por WhatsApp', 5, 'incoming,call,smartphone', 15),
  ('Cómo hacer una videollamada por WhatsApp', 6, 'hang,up,phone,call', 16),
  ('Cómo enviar una foto por WhatsApp', 1, 'whatsapp,chat,smartphone', 17),
  ('Cómo enviar una foto por WhatsApp', 2, 'attach,paperclip,smartphone', 18),
  ('Cómo enviar una foto por WhatsApp', 3, 'gallery,photos,smartphone', 19),
  ('Cómo enviar una foto por WhatsApp', 4, 'choosing,photo,smartphone', 20),
  ('Cómo enviar una foto por WhatsApp', 5, 'sending,photo,smartphone', 21),
  ('Cómo evitar estafas por WhatsApp', 1, 'prize,lottery,scam', 22),
  ('Cómo evitar estafas por WhatsApp', 2, 'scam,message,smartphone', 23),
  ('Cómo evitar estafas por WhatsApp', 3, 'security,code,smartphone', 24),
  ('Cómo evitar estafas por WhatsApp', 4, 'phishing,link,warning', 25),
  ('Cómo evitar estafas por WhatsApp', 5, 'senior,family,phone,help', 26),
  ('Cómo sacar una foto', 1, 'camera,smartphone', 27),
  ('Cómo sacar una foto', 2, 'taking,photo,smartphone', 28),
  ('Cómo sacar una foto', 3, 'focus,camera,smartphone', 29),
  ('Cómo sacar una foto', 4, 'shutter,button,smartphone', 30),
  ('Cómo sacar una foto', 5, 'photo,gallery,smartphone', 31),
  ('Cómo ver tus fotos guardadas', 1, 'photos,app,smartphone', 32),
  ('Cómo ver tus fotos guardadas', 2, 'recent,photos,smartphone', 33),
  ('Cómo ver tus fotos guardadas', 3, 'swipe,smartphone,screen', 34),
  ('Cómo ver tus fotos guardadas', 4, 'zoom,photo,smartphone', 35),
  ('Cómo ver tus fotos guardadas', 5, 'back,button,smartphone', 36),
  ('Cómo borrar fotos para liberar espacio', 1, 'photos,app,smartphone', 37),
  ('Cómo borrar fotos para liberar espacio', 2, 'blurry,photo', 38),
  ('Cómo borrar fotos para liberar espacio', 3, 'long,press,smartphone,touch', 39),
  ('Cómo borrar fotos para liberar espacio', 4, 'trash,bin,delete', 40),
  ('Cómo borrar fotos para liberar espacio', 5, 'undo,smartphone', 41),
  ('Cómo aumentar el tamaño de la letra — Android', 1, 'settings,android,smartphone', 42),
  ('Cómo aumentar el tamaño de la letra — Android', 2, 'display,settings,smartphone', 43),
  ('Cómo aumentar el tamaño de la letra — Android', 3, 'font,size,smartphone', 44),
  ('Cómo aumentar el tamaño de la letra — Android', 4, 'slider,settings,smartphone', 45),
  ('Cómo aumentar el tamaño de la letra — Android', 5, 'large,icons,smartphone', 46),
  ('Cómo aumentar el tamaño de la letra — iPhone', 1, 'settings,iphone', 47),
  ('Cómo aumentar el tamaño de la letra — iPhone', 2, 'accessibility,iphone', 48),
  ('Cómo aumentar el tamaño de la letra — iPhone', 3, 'text,size,iphone', 49),
  ('Cómo aumentar el tamaño de la letra — iPhone', 4, 'large,text,iphone', 50),
  ('Cómo aumentar el tamaño de la letra — iPhone', 5, 'slider,iphone,settings', 51),
  ('Cómo conectarte a una red Wi-Fi — Android', 1, 'settings,android,smartphone', 52),
  ('Cómo conectarte a una red Wi-Fi — Android', 2, 'wifi,smartphone', 53),
  ('Cómo conectarte a una red Wi-Fi — Android', 3, 'wifi,switch,smartphone', 54),
  ('Cómo conectarte a una red Wi-Fi — Android', 4, 'wifi,router', 55),
  ('Cómo conectarte a una red Wi-Fi — Android', 5, 'password,smartphone,typing', 56),
  ('Cómo conectarte a una red Wi-Fi — iPhone', 1, 'settings,iphone', 57),
  ('Cómo conectarte a una red Wi-Fi — iPhone', 2, 'wifi,iphone', 58),
  ('Cómo conectarte a una red Wi-Fi — iPhone', 3, 'wifi,switch,iphone', 59),
  ('Cómo conectarte a una red Wi-Fi — iPhone', 4, 'wifi,router', 60),
  ('Cómo conectarte a una red Wi-Fi — iPhone', 5, 'password,iphone,typing', 61),
  ('Cómo subir y bajar el volumen del celular', 1, 'smartphone,side,buttons', 62),
  ('Cómo subir y bajar el volumen del celular', 2, 'volume,up,smartphone', 63),
  ('Cómo subir y bajar el volumen del celular', 3, 'volume,down,smartphone', 64),
  ('Cómo subir y bajar el volumen del celular', 4, 'volume,slider,smartphone', 65),
  ('Cómo subir y bajar el volumen del celular', 5, 'silent,mute,smartphone', 66),
  ('Cómo conectar auriculares Bluetooth', 1, 'wireless,earbuds,case', 67),
  ('Cómo conectar auriculares Bluetooth', 2, 'settings,smartphone', 68),
  ('Cómo conectar auriculares Bluetooth', 3, 'bluetooth,smartphone', 69),
  ('Cómo conectar auriculares Bluetooth', 4, 'bluetooth,switch,smartphone', 70),
  ('Cómo conectar auriculares Bluetooth', 5, 'wireless,headphones,smartphone', 71),
  ('Cómo hacer una captura de pantalla — Android', 1, 'android,smartphone,buttons', 72),
  ('Cómo hacer una captura de pantalla — Android', 2, 'pressing,buttons,smartphone', 73),
  ('Cómo hacer una captura de pantalla — Android', 3, 'screenshot,smartphone', 74),
  ('Cómo hacer una captura de pantalla — Android', 4, 'gallery,screenshot,smartphone', 75),
  ('Cómo hacer una captura de pantalla — Android', 5, 'whatsapp,share,smartphone', 76),
  ('Cómo hacer una captura de pantalla — iPhone', 1, 'iphone,buttons', 77),
  ('Cómo hacer una captura de pantalla — iPhone', 2, 'pressing,buttons,iphone', 78),
  ('Cómo hacer una captura de pantalla — iPhone', 3, 'screenshot,iphone', 79),
  ('Cómo hacer una captura de pantalla — iPhone', 4, 'photos,iphone', 80),
  ('Cómo hacer una captura de pantalla — iPhone', 5, 'whatsapp,share,iphone', 81),
  ('Cómo hacer una llamada desde el celular', 1, 'phone,app,smartphone', 82),
  ('Cómo hacer una llamada desde el celular', 2, 'contacts,smartphone', 83),
  ('Cómo hacer una llamada desde el celular', 3, 'contact,list,smartphone', 84),
  ('Cómo hacer una llamada desde el celular', 4, 'green,call,button,phone', 85),
  ('Cómo hacer una llamada desde el celular', 5, 'hang,up,phone,call', 86),
  ('Cómo identificar una llamada sospechosa', 1, 'unknown,number,phone,call', 87),
  ('Cómo identificar una llamada sospechosa', 2, 'worried,senior,phone', 88),
  ('Cómo identificar una llamada sospechosa', 3, 'personal,data,phone,scam', 89),
  ('Cómo identificar una llamada sospechosa', 4, 'install,app,smartphone,warning', 90),
  ('Cómo identificar una llamada sospechosa', 5, 'senior,phone,hang,up', 91),
  ('Cómo buscar algo en Google', 1, 'google,search,smartphone', 92),
  ('Cómo buscar algo en Google', 2, 'search,bar,smartphone', 93),
  ('Cómo buscar algo en Google', 3, 'typing,question,smartphone', 94),
  ('Cómo buscar algo en Google', 4, 'search,button,keyboard', 95),
  ('Cómo buscar algo en Google', 5, 'voice,search,microphone', 96),
  ('Qué hacer cuando el celular no tiene Internet', 1, 'smartphone,status,bar', 97),
  ('Qué hacer cuando el celular no tiene Internet', 2, 'wifi,settings,smartphone', 98),
  ('Qué hacer cuando el celular no tiene Internet', 3, 'mobile,data,smartphone', 99),
  ('Qué hacer cuando el celular no tiene Internet', 4, 'airplane,mode,smartphone', 100),
  ('Qué hacer cuando el celular no tiene Internet', 5, 'restart,smartphone,power,button', 101)
) AS k(titulo, orden, tags, lock_id)
JOIN tutoriales t ON t.titulo = k.titulo AND t.deleted_at IS NULL
WHERE p.tutorial_id = t.id
  AND p.orden = k.orden
  AND p.imagen_url IS NULL;
